config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout',                  to: 'sessions#destroy'
  get '/auth/failure',            to: redirect('/')

  resources :users do
    get '/review_for/:date(/:old_date)', to: 'items#review', as: :review
    get '/monthly_review_for/:month(/:old_month)', to: 'items#monthly_review', as: :monthly_review
    get '/accounts(/:month)', to: 'accounts#index', as: :accounts

    resources :accounts do
      resources :items
    end
  end

  root 'welcome#index'
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  has_many   :items
  
  validates :name, presence: true

  default_scope { order('accounts.created_at desc') }
  scope :with_items_bought_in, -> (month, accounts = all) { accounts.select { |account| account.items.bought_in(month).any? } }

  def left_money(abs = true, month = :this_month)
    left_money = money - items.bought_in(month).sum(:total)
    abs ? left_money.abs : left_money
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user
  before_action :set_user
  before_action :set_accounts
  before_action :check_ownership

  def index
    @month = params[:month] || :this_month

    respond_to do |format|
      format.html

      format.json { render json: @accounts, include: :items }

      format.xml { render xml: @accounts, include: :items }
    end
  end

  def create
    @accounts.create account_params
    redirect_to user_accounts_url(@user)
  end

  def update
    @user.accounts.find(params[:id]).update(account_params.except(:id))
    redirect_to :back
  end

  def destroy
    redirect_to user_accounts_url(@user)
  end

private

  def account_params
    params.required(:account).permit(:id, :name, :money)
  end

  def set_user
    @user = User.find params[:user_id]
  end

  def set_accounts
    @accounts = params[:month].presence ? @user.accounts.with_items_bought_in(params[:month]) : @user.accounts
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def currency_info_for(account)
    { unit: account.currency }
  end
end

app/views/accounts/_account.html.erb
<div class="account">
  <h2>
    <%= account.name %>
    <br>
    <%= number_to_currency(account.money, currency_info_for(@user)) %>
    <% if account.left_money(false) != account.money %>
      (<%= "#{number_to_currency(account.left_money(true, @month), currency_info_for(@user))} #{account.left_money(false, @month) > 0 ? 'left' : 'of debt'}" %>)
    <% end %>
  </h2>

  <div class="items">
    <% account.items.bought_in(@month).each do |item| %>
      <%= render 'item', item: item, account: account %>
    <% end %>
  </div>

  <%= render 'new_item',     account: account %>
  <%= render 'edit_account', account: account %>
</div>

app/views/accounts/_edit_account.html.erb
<div id="edit-account-modal-form-for-<%= account.to_param %>" class="edit-account modal-form">
  <%= simple_form_for [@user, account], data: { validate: 'parsley' } do |f| %>
    <%= f.input :id, as: :hidden, input_html: { value: account.id } %>

    <%= f.input :name  %>
    <%= f.input :money %>

    <%= f.button :submit, 'Edit account', class: 'button teal' %>
  <% end %>
</div>

<%= link_to_modal 'Edit account', "#edit-account-modal-form-for-#{account.to_param}", class: 'btn button teal modal-form' %>

app/views/accounts/_item.html.erb
<div class="item">
  <span><%= item.name_and_quantity %>: <%= number_to_currency(item.total, currency_info_for(@user)) %> (the <%= item.bought_at.strftime("%y/%m/%d at %H:%M") %>)</span> <%= raw("<span>#{item.details}</span>") if item.details.present? %> (<%= link_to 'X', user_account_item_path(@user, account, item), method: :delete, data: { confirm: 'Are you sure?' } %>)
</div>

app/views/accounts/_new_account.html.erb
<div id="new-account-modal-form" class="new-account modal-form">
  <h2>New account</h2>

  <%= simple_form_for :account, data: { validate: 'parsley' } do |f| %>
    <%= f.input :name     %>
    <%= f.input :money    %>

    <%= f.button :submit, 'Create account', class: 'button teal' %>
  <% end %>
</div>

app/views/accounts/_new_item.html.erb
<div id="new-item-modal-form-for-<%= account.to_param %>" class="new-item modal-form">
  <%= simple_form_for [@user, account, account.items.build], data: { validate: 'parsley' } do |f| %>
    <%= f.input :name     %>
    <%= f.input :quantity %>
    <%= f.input :price    %>
    <%= f.input :details  %>

    <%= f.button :submit, 'Add item', class: 'button teal' %>
  <% end %>
</div>

<%= link_to_modal 'Add new item', "#new-item-modal-form-for-#{account.to_param}", class: 'btn button teal modal-form' %>

app/views/accounts/index.html.erb
<div id="contents-header">
  <h1>Your accounts</h1>

  <%= link_to_modal 'New account', '#new-account-modal-form', class: 'btn button teal' %>

  <%= link_to_modal 'This month', user_monthly_review_path(@user, :this_month, @month.is_a?(Symbol) ? :the_previous_month : @month), class: 'btn button teal' %>
  
  <% if @month == :this_month %>
    <%= link_to_modal 'Today', user_review_path(@user, Date.today, Date.yesterday), class: 'btn button teal' %>
  <% end %>
</div>

<div class="accounts-grid">
  <% @accounts.sort_by(&:name).each do |account| %>
    <%= render 'account', account: account %>
  <% end %>
  
  <%= render 'new_account' %>
</div>

<footer>
  <%= simple_form_for '#', url: user_accounts_url(@user) do |f| %>
    <%= f.input :date, input_html: { id: 'date' } %>
  <% end %>
</footer>